name: CI

on:
  pull_request:
    paths:
      - 'asynchronous-janken/**'
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths:
      - 'asynchronous-janken/**'
      - '.github/workflows/**'

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: asynchronous-janken
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        run: corepack prepare pnpm@9 --activate

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('asynchronous-janken/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build
